version: "3.3"
services:

    #######################################################
    #  Gateway
    #######################################################
  gateway:
    image: gateway
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/ApiGateway/Airline.ApiGateway/Dockerfile
    container_name: airline-gateway
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - airline


    #######################################################
    #  Flight
    #######################################################
  flight:
    image: flight
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Airline.Flight/Dockerfile
    container_name: airline-flight
    ports:
      - 5004:80
      - 5003:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5003
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - airline


    #######################################################
    #  Identity
    #######################################################
  identity:
    image: identity
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Airline.Identity/Dockerfile
    container_name: airline-identity
    ports:
      - 6005:80
      - 5005:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5005
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - airline


    #######################################################
    #  Passenger
    #######################################################
  passenger:
    image: passenger
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Airline.Passenger/Dockerfile
    container_name: airline-passenger
    ports:
      - 6012:80
      - 5012:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5012
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - airline


    #######################################################
    #  Reservation
    #######################################################
  reservation:
    image: reservation
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Airline.Reservation/Dockerfile
    container_name: airline-reservation
    ports:
      - 6010:80
      - 5010:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5010
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - airline


networks:
  airline:
    name: airline

volumes:
  db-data:
    external: false

